// Code generated by MockGen. DO NOT EDIT.
// Source: product_service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	product "go-sqlc-starter/internal/api/v1/product"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, req product.CreateProductRequest) (product.ProductAdminResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(product.ProductAdminResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, id)
}

// GetByIDAdmin mocks base method.
func (m *MockService) GetByIDAdmin(ctx context.Context, id string) (product.ProductAdminResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDAdmin", ctx, id)
	ret0, _ := ret[0].(product.ProductAdminResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDAdmin indicates an expected call of GetByIDAdmin.
func (mr *MockServiceMockRecorder) GetByIDAdmin(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDAdmin", reflect.TypeOf((*MockService)(nil).GetByIDAdmin), ctx, id)
}

// ListAdmin mocks base method.
func (m *MockService) ListAdmin(ctx context.Context, page, limit int, search, sortCol, categoryID string) ([]product.ProductAdminResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdmin", ctx, page, limit, search, sortCol, categoryID)
	ret0, _ := ret[0].([]product.ProductAdminResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAdmin indicates an expected call of ListAdmin.
func (mr *MockServiceMockRecorder) ListAdmin(ctx, page, limit, search, sortCol, categoryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdmin", reflect.TypeOf((*MockService)(nil).ListAdmin), ctx, page, limit, search, sortCol, categoryID)
}

// ListPublic mocks base method.
func (m *MockService) ListPublic(ctx context.Context, req product.ListPublicRequest) ([]product.ProductPublicResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublic", ctx, req)
	ret0, _ := ret[0].([]product.ProductPublicResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPublic indicates an expected call of ListPublic.
func (mr *MockServiceMockRecorder) ListPublic(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublic", reflect.TypeOf((*MockService)(nil).ListPublic), ctx, req)
}

// Restore mocks base method.
func (m *MockService) Restore(ctx context.Context, id string) (product.ProductAdminResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(product.ProductAdminResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockServiceMockRecorder) Restore(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockService)(nil).Restore), ctx, id)
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, id string, req product.UpdateProductRequest) (product.ProductAdminResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(product.ProductAdminResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, id, req)
}
