// Code generated by MockGen. DO NOT EDIT.
// Source: product_service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	product "go-sqlc-starter/internal/api/v1/product"
	dbgen "go-sqlc-starter/internal/dbgen"
	multipart "mime/multipart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockReviewRepository is a mock of ReviewRepository interface.
type MockReviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewRepositoryMockRecorder
}

// MockReviewRepositoryMockRecorder is the mock recorder for MockReviewRepository.
type MockReviewRepositoryMockRecorder struct {
	mock *MockReviewRepository
}

// NewMockReviewRepository creates a new mock instance.
func NewMockReviewRepository(ctrl *gomock.Controller) *MockReviewRepository {
	mock := &MockReviewRepository{ctrl: ctrl}
	mock.recorder = &MockReviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewRepository) EXPECT() *MockReviewRepositoryMockRecorder {
	return m.recorder
}

// CountByProductID mocks base method.
func (m *MockReviewRepository) CountByProductID(ctx context.Context, productID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByProductID", ctx, productID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByProductID indicates an expected call of CountByProductID.
func (mr *MockReviewRepositoryMockRecorder) CountByProductID(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByProductID", reflect.TypeOf((*MockReviewRepository)(nil).CountByProductID), ctx, productID)
}

// GetAverageRating mocks base method.
func (m *MockReviewRepository) GetAverageRating(ctx context.Context, productID uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAverageRating", ctx, productID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAverageRating indicates an expected call of GetAverageRating.
func (mr *MockReviewRepositoryMockRecorder) GetAverageRating(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAverageRating", reflect.TypeOf((*MockReviewRepository)(nil).GetAverageRating), ctx, productID)
}

// GetByProductID mocks base method.
func (m *MockReviewRepository) GetByProductID(ctx context.Context, productID uuid.UUID, limit, offset int32) ([]dbgen.GetReviewsByProductIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProductID", ctx, productID, limit, offset)
	ret0, _ := ret[0].([]dbgen.GetReviewsByProductIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProductID indicates an expected call of GetByProductID.
func (mr *MockReviewRepositoryMockRecorder) GetByProductID(ctx, productID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProductID", reflect.TypeOf((*MockReviewRepository)(nil).GetByProductID), ctx, productID, limit, offset)
}

// MockCloudinaryService is a mock of CloudinaryService interface.
type MockCloudinaryService struct {
	ctrl     *gomock.Controller
	recorder *MockCloudinaryServiceMockRecorder
}

// MockCloudinaryServiceMockRecorder is the mock recorder for MockCloudinaryService.
type MockCloudinaryServiceMockRecorder struct {
	mock *MockCloudinaryService
}

// NewMockCloudinaryService creates a new mock instance.
func NewMockCloudinaryService(ctrl *gomock.Controller) *MockCloudinaryService {
	mock := &MockCloudinaryService{ctrl: ctrl}
	mock.recorder = &MockCloudinaryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudinaryService) EXPECT() *MockCloudinaryServiceMockRecorder {
	return m.recorder
}

// DeleteImage mocks base method.
func (m *MockCloudinaryService) DeleteImage(ctx context.Context, publicID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", ctx, publicID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockCloudinaryServiceMockRecorder) DeleteImage(ctx, publicID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockCloudinaryService)(nil).DeleteImage), ctx, publicID)
}

// UploadImage mocks base method.
func (m *MockCloudinaryService) UploadImage(ctx context.Context, file multipart.File, filename, folderName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, file, filename, folderName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockCloudinaryServiceMockRecorder) UploadImage(ctx, file, filename, folderName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockCloudinaryService)(nil).UploadImage), ctx, file, filename, folderName)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, req product.CreateProductRequest, file multipart.File, filename string) (product.ProductAdminResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req, file, filename)
	ret0, _ := ret[0].(product.ProductAdminResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, req, file, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, req, file, filename)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockService) GetByID(ctx context.Context, id string) (product.ProductAdminResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(product.ProductAdminResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), ctx, id)
}

// GetBySlug mocks base method.
func (m *MockService) GetBySlug(ctx context.Context, slug string) (product.ProductDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(product.ProductDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockServiceMockRecorder) GetBySlug(ctx, slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockService)(nil).GetBySlug), ctx, slug)
}

// ListAdmin mocks base method.
func (m *MockService) ListAdmin(ctx context.Context, req product.ListProductAdminRequest) ([]product.ProductAdminResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdmin", ctx, req)
	ret0, _ := ret[0].([]product.ProductAdminResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAdmin indicates an expected call of ListAdmin.
func (mr *MockServiceMockRecorder) ListAdmin(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdmin", reflect.TypeOf((*MockService)(nil).ListAdmin), ctx, req)
}

// ListPublic mocks base method.
func (m *MockService) ListPublic(ctx context.Context, req product.ListPublicRequest) ([]product.ProductPublicResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublic", ctx, req)
	ret0, _ := ret[0].([]product.ProductPublicResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPublic indicates an expected call of ListPublic.
func (mr *MockServiceMockRecorder) ListPublic(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublic", reflect.TypeOf((*MockService)(nil).ListPublic), ctx, req)
}

// Restore mocks base method.
func (m *MockService) Restore(ctx context.Context, id string) (product.ProductAdminResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx, id)
	ret0, _ := ret[0].(product.ProductAdminResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockServiceMockRecorder) Restore(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockService)(nil).Restore), ctx, id)
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, idStr string, req product.UpdateProductRequest, file multipart.File, filename string) (product.ProductAdminResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, idStr, req, file, filename)
	ret0, _ := ret[0].(product.ProductAdminResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, idStr, req, file, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, idStr, req, file, filename)
}
