// Code generated by MockGen. DO NOT EDIT.
// Source: review_service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	review "go-sqlc-starter/internal/api/v1/review"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CheckEligibility mocks base method.
func (m *MockService) CheckEligibility(ctx context.Context, userID, productSlug string) (review.ReviewEligibilityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEligibility", ctx, userID, productSlug)
	ret0, _ := ret[0].(review.ReviewEligibilityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckEligibility indicates an expected call of CheckEligibility.
func (mr *MockServiceMockRecorder) CheckEligibility(ctx, userID, productSlug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEligibility", reflect.TypeOf((*MockService)(nil).CheckEligibility), ctx, userID, productSlug)
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, userID, productSlug string, req review.CreateReviewRequest) (review.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, productSlug, req)
	ret0, _ := ret[0].(review.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, userID, productSlug, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, userID, productSlug, req)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, reviewID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, reviewID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, reviewID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, reviewID, userID)
}

// GetByProductSlug mocks base method.
func (m *MockService) GetByProductSlug(ctx context.Context, productSlug string, page, limit int) (review.ReviewListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProductSlug", ctx, productSlug, page, limit)
	ret0, _ := ret[0].(review.ReviewListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProductSlug indicates an expected call of GetByProductSlug.
func (mr *MockServiceMockRecorder) GetByProductSlug(ctx, productSlug, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProductSlug", reflect.TypeOf((*MockService)(nil).GetByProductSlug), ctx, productSlug, page, limit)
}

// GetByUserID mocks base method.
func (m *MockService) GetByUserID(ctx context.Context, userID string, page, limit int) (review.UserReviewListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, page, limit)
	ret0, _ := ret[0].(review.UserReviewListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockServiceMockRecorder) GetByUserID(ctx, userID, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockService)(nil).GetByUserID), ctx, userID, page, limit)
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, reviewID, userID string, req review.UpdateReviewRequest) (review.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, reviewID, userID, req)
	ret0, _ := ret[0].(review.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, reviewID, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, reviewID, userID, req)
}
