// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brands.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO brands (name, slug, description, image_url)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, description, image_url, is_active, created_at, updated_at, deleted_at
`

type CreateBrandParams struct {
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error) {
	row := q.queryRow(ctx, q.createBrandStmt, createBrand,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
	)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, name, slug, description, image_url, is_active, created_at, updated_at, deleted_at FROM brands WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetBrandByID(ctx context.Context, id uuid.UUID) (Brand, error) {
	row := q.queryRow(ctx, q.getBrandByIDStmt, getBrandByID, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBrandsAdmin = `-- name: ListBrandsAdmin :many
SELECT 
    id, name, slug, description, image_url, is_active, created_at, updated_at, deleted_at, 
    COUNT(*) OVER() AS total_count
FROM brands
WHERE 
    deleted_at IS NULL
    AND (
        $3::text IS NULL 
        OR name ILIKE '%' || $3::text || '%'
        OR description ILIKE '%' || $3::text || '%'
    )
ORDER BY 
    -- Group 1: Sort berdasarkan STRING (Name, dll)
    CASE 
        WHEN $4::text = 'name' AND $5::text = 'asc' THEN name 
    END ASC,
    CASE 
        WHEN $4::text = 'name' AND $5::text = 'desc' THEN name 
    END DESC,

    -- Group 2: Sort berdasarkan TIMESTAMP (Created At)
    -- Kita pisahkan grup CASE agar tipe data tidak bentrok
    CASE 
        WHEN $4::text = 'created_at' AND $5::text = 'asc' THEN created_at 
    END ASC,
    CASE 
        WHEN ($4::text = 'created_at' AND $5::text = 'desc') 
             OR ($4::text NOT IN ('name', 'created_at')) -- Fallback Logic di sini
             THEN created_at 
    END DESC
LIMIT $1 OFFSET $2
`

type ListBrandsAdminParams struct {
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
	Search  sql.NullString `json:"search"`
	SortCol string         `json:"sort_col"`
	SortDir string         `json:"sort_dir"`
}

type ListBrandsAdminRow struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	TotalCount  int64          `json:"total_count"`
}

func (q *Queries) ListBrandsAdmin(ctx context.Context, arg ListBrandsAdminParams) ([]ListBrandsAdminRow, error) {
	rows, err := q.query(ctx, q.listBrandsAdminStmt, listBrandsAdmin,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.SortCol,
		arg.SortDir,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBrandsAdminRow
	for rows.Next() {
		var i ListBrandsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrandsPublic = `-- name: ListBrandsPublic :many
SELECT id, name, slug, description, image_url, is_active, created_at, updated_at, deleted_at, count(*) OVER() AS total_count
FROM brands
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBrandsPublicParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListBrandsPublicRow struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	TotalCount  int64          `json:"total_count"`
}

func (q *Queries) ListBrandsPublic(ctx context.Context, arg ListBrandsPublicParams) ([]ListBrandsPublicRow, error) {
	rows, err := q.query(ctx, q.listBrandsPublicStmt, listBrandsPublic, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBrandsPublicRow
	for rows.Next() {
		var i ListBrandsPublicRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreBrand = `-- name: RestoreBrand :one
UPDATE brands SET deleted_at = NULL WHERE id = $1 RETURNING id, name, slug, description, image_url, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreBrand(ctx context.Context, id uuid.UUID) (Brand, error) {
	row := q.queryRow(ctx, q.restoreBrandStmt, restoreBrand, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteBrand = `-- name: SoftDeleteBrand :exec
UPDATE brands SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteBrand(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.softDeleteBrandStmt, softDeleteBrand, id)
	return err
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE brands 
SET name = $2, slug = $3, description = $4, image_url = $5, is_active = $6, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, description, image_url, is_active, created_at, updated_at, deleted_at
`

type UpdateBrandParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	IsActive    sql.NullBool   `json:"is_active"`
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error) {
	row := q.queryRow(ctx, q.updateBrandStmt, updateBrand,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
