// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carts.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countCartItems = `-- name: CountCartItems :one
SELECT COALESCE(SUM(quantity), 0)::bigint
FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) CountCartItems(ctx context.Context, cartID uuid.UUID) (int64, error) {
	row := q.queryRow(ctx, q.countCartItemsStmt, countCartItems, cartID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, created_at, updated_at, deleted_at
`

func (q *Queries) CreateCart(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.queryRow(ctx, q.createCartStmt, createCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO cart_items (cart_id, product_id, quantity, price_at_add)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cart_id, product_id)
DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity
RETURNING id, cart_id, product_id, quantity, price_at_add, created_at, updated_at, deleted_at
`

type CreateCartItemParams struct {
	CartID     uuid.UUID `json:"cart_id"`
	ProductID  uuid.UUID `json:"product_id"`
	Quantity   int32     `json:"quantity"`
	PriceAtAdd int32     `json:"price_at_add"`
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error) {
	row := q.queryRow(ctx, q.createCartItemStmt, createCartItem,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceAtAdd,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceAtAdd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM carts WHERE id = $1
`

func (q *Queries) DeleteCart(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteCartStmt, deleteCart, id)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items WHERE cart_id = $1 AND id = $2
`

type DeleteCartItemParams struct {
	CartID uuid.UUID `json:"cart_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.exec(ctx, q.deleteCartItemStmt, deleteCartItem, arg.CartID, arg.ID)
	return err
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT id, user_id, created_at, updated_at, deleted_at FROM carts WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.queryRow(ctx, q.getCartByUserIDStmt, getCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCartDetail = `-- name: GetCartDetail :many
SELECT
    ci.id,
    ci.product_id,
    ci.quantity,
    ci.price_at_add,
    ci.created_at
FROM carts c
JOIN cart_items ci ON ci.cart_id = c.id
WHERE c.user_id = $1
ORDER BY ci.created_at DESC
`

type GetCartDetailRow struct {
	ID         uuid.UUID `json:"id"`
	ProductID  uuid.UUID `json:"product_id"`
	Quantity   int32     `json:"quantity"`
	PriceAtAdd int32     `json:"price_at_add"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) GetCartDetail(ctx context.Context, userID uuid.UUID) ([]GetCartDetailRow, error) {
	rows, err := q.query(ctx, q.getCartDetailStmt, getCartDetail, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartDetailRow
	for rows.Next() {
		var i GetCartDetailRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Quantity,
			&i.PriceAtAdd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItemQty = `-- name: UpdateCartItemQty :one
UPDATE cart_items
SET quantity = $3, updated_at = NOW()
WHERE cart_id = $1 AND id = $2
RETURNING id, cart_id, product_id, quantity, price_at_add, created_at, updated_at, deleted_at
`

type UpdateCartItemQtyParams struct {
	CartID   uuid.UUID `json:"cart_id"`
	ID       uuid.UUID `json:"id"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) UpdateCartItemQty(ctx context.Context, arg UpdateCartItemQtyParams) (CartItem, error) {
	row := q.queryRow(ctx, q.updateCartItemQtyStmt, updateCartItemQty, arg.CartID, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceAtAdd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
