// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Address struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	Label          string         `json:"label"`
	RecipientName  string         `json:"recipient_name"`
	RecipientPhone string         `json:"recipient_phone"`
	Street         string         `json:"street"`
	Subdistrict    sql.NullString `json:"subdistrict"`
	District       sql.NullString `json:"district"`
	City           sql.NullString `json:"city"`
	Province       sql.NullString `json:"province"`
	PostalCode     sql.NullString `json:"postal_code"`
	IsPrimary      bool           `json:"is_primary"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

type Brand struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type Cart struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type CartItem struct {
	ID         uuid.UUID    `json:"id"`
	CartID     uuid.UUID    `json:"cart_id"`
	ProductID  uuid.UUID    `json:"product_id"`
	Quantity   int32        `json:"quantity"`
	PriceAtAdd int32        `json:"price_at_add"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

type Category struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type Order struct {
	ID              uuid.UUID       `json:"id"`
	OrderNumber     string          `json:"order_number"`
	UserID          uuid.UUID       `json:"user_id"`
	Status          string          `json:"status"`
	PaymentMethod   sql.NullString  `json:"payment_method"`
	PaymentStatus   string          `json:"payment_status"`
	AddressSnapshot json.RawMessage `json:"address_snapshot"`
	SubtotalPrice   string          `json:"subtotal_price"`
	DiscountPrice   string          `json:"discount_price"`
	ShippingPrice   string          `json:"shipping_price"`
	TotalPrice      string          `json:"total_price"`
	Note            sql.NullString  `json:"note"`
	PlacedAt        time.Time       `json:"placed_at"`
	PaidAt          sql.NullTime    `json:"paid_at"`
	CancelledAt     sql.NullTime    `json:"cancelled_at"`
	CancelReason    sql.NullString  `json:"cancel_reason"`
	CompletedAt     sql.NullTime    `json:"completed_at"`
	ReceiptNo       sql.NullString  `json:"receipt_no"`
	SnapToken       sql.NullString  `json:"snap_token"`
	SnapRedirectUrl sql.NullString  `json:"snap_redirect_url"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	DeletedAt       sql.NullTime    `json:"deleted_at"`
}

type OrderItem struct {
	ID           uuid.UUID `json:"id"`
	OrderID      uuid.UUID `json:"order_id"`
	ProductID    uuid.UUID `json:"product_id"`
	NameSnapshot string    `json:"name_snapshot"`
	UnitPrice    string    `json:"unit_price"`
	Quantity     int32     `json:"quantity"`
	TotalPrice   string    `json:"total_price"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Product struct {
	ID          uuid.UUID      `json:"id"`
	CategoryID  uuid.UUID      `json:"category_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	Sku         sql.NullString `json:"sku"`
	ImageUrl    sql.NullString `json:"image_url"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type Review struct {
	ID                 uuid.UUID    `json:"id"`
	UserID             uuid.UUID    `json:"user_id"`
	ProductID          uuid.UUID    `json:"product_id"`
	OrderID            uuid.UUID    `json:"order_id"`
	Rating             int32        `json:"rating"`
	Comment            string       `json:"comment"`
	IsVerifiedPurchase bool         `json:"is_verified_purchase"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          time.Time    `json:"updated_at"`
	DeletedAt          sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Password  string    `json:"password"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}
