// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (category_id, name, slug, description, price, stock, sku, image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, category_id, name, slug, description, price, stock, sku, image_url, is_active, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	CategoryID  uuid.UUID      `json:"category_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	Sku         sql.NullString `json:"sku"`
	ImageUrl    sql.NullString `json:"image_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.queryRow(ctx, q.createProductStmt, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.Sku,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.stock, p.sku, p.image_url, p.is_active, p.created_at, p.updated_at, p.deleted_at, c.name as category_name 
FROM products p
JOIN categories c ON p.category_id = c.id
WHERE p.id = $1 AND p.deleted_at IS NULL LIMIT 1
`

type GetProductByIDRow struct {
	ID           uuid.UUID      `json:"id"`
	CategoryID   uuid.UUID      `json:"category_id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	Price        string         `json:"price"`
	Stock        int32          `json:"stock"`
	Sku          sql.NullString `json:"sku"`
	ImageUrl     sql.NullString `json:"image_url"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	CategoryName string         `json:"category_name"`
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.queryRow(ctx, q.getProductByIDStmt, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategoryName,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.stock, p.sku, p.image_url, p.is_active, p.created_at, p.updated_at, p.deleted_at, c.name as category_name 
FROM products p
JOIN categories c ON p.category_id = c.id
WHERE p.slug = $1 AND p.deleted_at IS NULL LIMIT 1
`

type GetProductBySlugRow struct {
	ID           uuid.UUID      `json:"id"`
	CategoryID   uuid.UUID      `json:"category_id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	Price        string         `json:"price"`
	Stock        int32          `json:"stock"`
	Sku          sql.NullString `json:"sku"`
	ImageUrl     sql.NullString `json:"image_url"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	CategoryName string         `json:"category_name"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.queryRow(ctx, q.getProductBySlugStmt, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CategoryName,
	)
	return i, err
}

const listProductsAdmin = `-- name: ListProductsAdmin :many
SELECT
    p.id, p.category_id, p.name, p.slug, p.description, p.price, p.stock, p.sku, p.image_url, p.is_active, p.created_at, p.updated_at, p.deleted_at,
    c.name AS category_name,
    COUNT(*) OVER() AS total_count
FROM products p
JOIN categories c ON p.category_id = c.id
WHERE
    ($3::uuid IS NULL OR p.category_id = $3::uuid)
    AND (
        $4::text IS NULL
        OR p.name ILIKE '%' || $4::text || '%'
        OR p.sku  ILIKE '%' || $4::text || '%'
    )
ORDER BY
    -- name
    CASE
        WHEN $5 = 'name' AND $6 = 'asc'
            THEN p.name
    END ASC,
    CASE
        WHEN $5 = 'name' AND $6 = 'desc'
            THEN p.name
    END DESC,

    -- stock
    CASE
        WHEN $5 = 'stock' AND $6 = 'asc'
            THEN p.stock
    END ASC,
    CASE
        WHEN $5 = 'stock' AND $6 = 'desc'
            THEN p.stock
    END DESC,

    -- price
    CASE
        WHEN $5 = 'price' AND $6 = 'asc'
            THEN p.price
    END ASC,
    CASE
        WHEN $5 = 'price' AND $6 = 'desc'
            THEN p.price
    END DESC,

    -- fallback (default)
    p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsAdminParams struct {
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
	CategoryID uuid.NullUUID  `json:"category_id"`
	Search     sql.NullString `json:"search"`
	SortCol    interface{}    `json:"sort_col"`
	SortDir    interface{}    `json:"sort_dir"`
}

type ListProductsAdminRow struct {
	ID           uuid.UUID      `json:"id"`
	CategoryID   uuid.UUID      `json:"category_id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	Price        string         `json:"price"`
	Stock        int32          `json:"stock"`
	Sku          sql.NullString `json:"sku"`
	ImageUrl     sql.NullString `json:"image_url"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	CategoryName string         `json:"category_name"`
	TotalCount   int64          `json:"total_count"`
}

func (q *Queries) ListProductsAdmin(ctx context.Context, arg ListProductsAdminParams) ([]ListProductsAdminRow, error) {
	rows, err := q.query(ctx, q.listProductsAdminStmt, listProductsAdmin,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Search,
		arg.SortCol,
		arg.SortDir,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsAdminRow
	for rows.Next() {
		var i ListProductsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.Sku,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsPublic = `-- name: ListProductsPublic :many
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.stock, p.sku, p.image_url, p.is_active, p.created_at, p.updated_at, p.deleted_at, c.name as category_name, count(*) OVER() AS total_count
FROM products p
JOIN categories c ON p.category_id = c.id
WHERE p.deleted_at IS NULL 
  AND p.is_active = true
  -- Gunakan sintaks ini agar sqlc membuat field CategoryID (NullUUID)
  AND ($3::uuid IS NULL OR p.category_id = $3::uuid)
  AND ($4::text IS NULL OR p.name ILIKE '%' || $4::text || '%')
  AND (p.price >= $5::decimal)
  AND (p.price <= $6::decimal)
ORDER BY 
    CASE WHEN $7::text = 'newest' THEN p.created_at END DESC,
    CASE WHEN $7::text = 'oldest' THEN p.created_at END ASC,
    CASE WHEN $7::text = 'price_high' THEN p.price END DESC,
    CASE WHEN $7::text = 'price_low' THEN p.price END ASC,
    p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsPublicParams struct {
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
	CategoryID uuid.NullUUID  `json:"category_id"`
	Search     sql.NullString `json:"search"`
	MinPrice   string         `json:"min_price"`
	MaxPrice   string         `json:"max_price"`
	SortBy     string         `json:"sort_by"`
}

type ListProductsPublicRow struct {
	ID           uuid.UUID      `json:"id"`
	CategoryID   uuid.UUID      `json:"category_id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	Price        string         `json:"price"`
	Stock        int32          `json:"stock"`
	Sku          sql.NullString `json:"sku"`
	ImageUrl     sql.NullString `json:"image_url"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	CategoryName string         `json:"category_name"`
	TotalCount   int64          `json:"total_count"`
}

func (q *Queries) ListProductsPublic(ctx context.Context, arg ListProductsPublicParams) ([]ListProductsPublicRow, error) {
	rows, err := q.query(ctx, q.listProductsPublicStmt, listProductsPublic,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Search,
		arg.MinPrice,
		arg.MaxPrice,
		arg.SortBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsPublicRow
	for rows.Next() {
		var i ListProductsPublicRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.Sku,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProduct = `-- name: RestoreProduct :one
UPDATE products SET deleted_at = NULL WHERE id = $1 RETURNING id, category_id, name, slug, description, price, stock, sku, image_url, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.queryRow(ctx, q.restoreProductStmt, restoreProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.softDeleteProductStmt, softDeleteProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    category_id = $2,
    name = $3,
    description = $4,
    price = $5,
    stock = $6,
    sku = $7,
    image_url = $8,
    is_active = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, category_id, name, slug, description, price, stock, sku, image_url, is_active, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	ID          uuid.UUID      `json:"id"`
	CategoryID  uuid.UUID      `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	Sku         sql.NullString `json:"sku"`
	ImageUrl    sql.NullString `json:"image_url"`
	IsActive    sql.NullBool   `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.queryRow(ctx, q.updateProductStmt, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.Sku,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
