// Code generated by MockGen. DO NOT EDIT.
// Source: cart_service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	cart "go-sqlc-starter/internal/api/v1/cart"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockService) AddItem(ctx context.Context, userID string, req cart.AddItemRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockServiceMockRecorder) AddItem(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockService)(nil).AddItem), ctx, userID, req)
}

// Count mocks base method.
func (m *MockService) Count(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockServiceMockRecorder) Count(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockService)(nil).Count), ctx, userID)
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, userID)
}

// Decrement mocks base method.
func (m *MockService) Decrement(ctx context.Context, userID, productID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrement", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decrement indicates an expected call of Decrement.
func (mr *MockServiceMockRecorder) Decrement(ctx, userID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrement", reflect.TypeOf((*MockService)(nil).Decrement), ctx, userID, productID)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, userID)
}

// DeleteItem mocks base method.
func (m *MockService) DeleteItem(ctx context.Context, userID, productID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockServiceMockRecorder) DeleteItem(ctx, userID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockService)(nil).DeleteItem), ctx, userID, productID)
}

// Detail mocks base method.
func (m *MockService) Detail(ctx context.Context, userID string) (cart.CartDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, userID)
	ret0, _ := ret[0].(cart.CartDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockServiceMockRecorder) Detail(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockService)(nil).Detail), ctx, userID)
}

// Increment mocks base method.
func (m *MockService) Increment(ctx context.Context, userID, productID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Increment", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Increment indicates an expected call of Increment.
func (mr *MockServiceMockRecorder) Increment(ctx, userID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Increment", reflect.TypeOf((*MockService)(nil).Increment), ctx, userID, productID)
}

// UpdateQty mocks base method.
func (m *MockService) UpdateQty(ctx context.Context, userID, productID string, req cart.UpdateQtyRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQty", ctx, userID, productID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQty indicates an expected call of UpdateQty.
func (mr *MockServiceMockRecorder) UpdateQty(ctx, userID, productID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQty", reflect.TypeOf((*MockService)(nil).UpdateQty), ctx, userID, productID, req)
}
